/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // Manual top level so the external "Tutorials" link can sit between
  // Bluesky API and Relay (an autogenerated sidebar can't place a link
  // mid-list). The Bluesky API children stay autogenerated from its folder.
  tutorialSidebar: [
    // Protocol Services: the funnel target of the homepage hero's "Explore the
    // network" CTA. It introduces Bluesky's public protocol services and leads
    // straight into Jetstream — kept as the very next entry — as the place to
    // start.
    'protocol-services',
    {type: 'category', label: 'Jetstream', link: { type: 'doc', id: 'jetstream' }, items: ['jetstream-sdk', 'jetstream-replay', 'jetstream-webhooks', 'jetstream-analytics', 'jetstream-coop'] },
    {type: 'category', label: 'Relay', link: {type: 'doc', id: 'relay'}, items: ['consuming-the-firehose']},
    {
      // Children listed explicitly: a manual category doesn't apply the
      // "index = category link" convention to autogenerated items (index.mdx
      // would duplicate as a child), and this gives direct order control. Add
      // new Bluesky API pages here.
      type: 'category',
      // "Bluesky API" — the novice-friendly intro route, deemphasized in
      // favor of Jetstream but kept approachable. The directory and slug were
      // renamed get-started → bluesky-api to match this intent; old
      // /docs/get-started* URLs are preserved via client redirects.
      label: 'Bluesky API',
      // bpsGsPath: marks the three-item onboarding path (Bluesky API, About
      // Bluesky Content, Tutorials) so custom.css can tint it as a grouped
      // panel (see §4 sidebar styles).
      className: 'bpsGsPath bpsGsPath--first',
      link: { type: 'doc', id: 'bluesky-api/index' },
      collapsed: true,
      items: [
        'bluesky-api/creating-a-post',
        'bluesky-api/viewing-feeds',
        'bluesky-api/viewing-threads',
        'bluesky-api/like-repost',
        'bluesky-api/profiles',
        'bluesky-api/following',
        'bluesky-api/user-lists',
        'bluesky-api/custom-feeds',
        'bluesky-api/request-proxying',
      ],
    },
    {
      type: 'category',
      label: 'About Bluesky Content',
      className: 'bpsGsPath',
      link: { type: 'doc', id: 'about-bluesky-content/index' },
      items: [
        'about-bluesky-content/video',
        'about-bluesky-content/posts',
        'about-bluesky-content/post-richtext',
        'about-bluesky-content/timestamps',
        'about-bluesky-content/thread-gates',
        'oembed',
        'intent-links',
        'about-bluesky-content/app-integrations',
      ],
    },
    { type: 'link', label: 'HTTP Reference', className: 'bpsGsPath', href: 'https://endpoints.bsky.app' },
    { type: 'link', label: 'Tutorials', href: 'https://atproto.com/guides/tutorials', className: 'bpsGsPath bpsGsPath--last' },
    // A few related docs are nested under a parent doc to keep the top level
    // to ~9-10 items. The category links to the parent doc itself.
    { type: 'category', label: 'API Hosts and Auth', link: { type: 'doc', id: 'api-directory' }, items: ['rate-limits', 'resolving-identities', 'entryway', 'oauth-client']},
    'developer-guidelines',
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
