#!/usr/bin/env node
/**
 * Post-build assertions over ./build.
 *
 * `make test` previously ran only docusaurus-mdx-checker, which lints MDX
 * syntax and knows nothing about what the site actually emitted. Plenty of the
 * things that matter here are invisible to it: whether the blog rendered,
 * whether a legacy redirect stub survived a config edit, whether the head-tag
 * swizzle put its tags in the document. Those are the failures that reach
 * production quietly, so they get real assertions.
 *
 * Deliberately dependency-free and string-based. These check *emitted output*,
 * not implementation — a rewrite of the swizzle or the redirect list should
 * keep passing as long as the URLs and tags it owes the network are still there.
 *
 * Run after `make build`. Following this Makefile's convention, the build is
 * not run for you.
 */

import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'

const BUILD = path.resolve(import.meta.dirname, '..', 'build')

const failures = []
let checked = 0

function check(label, fn) {
  checked += 1
  try {
    const problem = fn()
    if (problem) failures.push(`${label}\n    ${problem}`)
  } catch (err) {
    failures.push(`${label}\n    threw: ${err.message}`)
  }
}

const at = (...parts) => path.join(BUILD, ...parts)

function read(rel) {
  const file = at(rel)
  if (!fs.existsSync(file)) return null
  return fs.readFileSync(file, 'utf8')
}

function exists(rel) {
  return fs.existsSync(at(rel)) ? null : `missing ${rel}`
}

// A page we own, as opposed to a meta-refresh stub left by the redirects
// plugin. `exists` alone is not enough: before the blog was reclaimed, /blog,
// /blog/archive and /blog/tags all "existed" as redirect stubs pointing at
// atproto.com, so a bare existence check passed while the page was absent.
// The rendered post/list body, excluding the site chrome. Assertions about what
// is NOT shown need this: the masthead and site footer legitimately contain the
// author name and links that would otherwise look like a byline.
function articleOf(rel) {
  const html = read(rel)
  if (html === null) return null
  const start = html.indexOf('<article')
  const end = html.lastIndexOf('</article>')
  return start === -1 || end === -1 ? null : html.slice(start, end)
}

function realPage(rel) {
  const html = read(rel)
  if (html === null) return `missing ${rel}`
  return html.includes('http-equiv="refresh"')
    ? `${rel} is a redirect stub, not a rendered page`
    : null
}

function contains(rel, needle) {
  const html = read(rel)
  if (html === null) return `missing ${rel}`
  return html.includes(needle)
    ? null
    : `${rel} does not contain ${JSON.stringify(needle)}`
}

if (!fs.existsSync(BUILD)) {
  console.error('No ./build directory. Run `make build` first.')
  process.exit(1)
}

// ---- Site baseline -------------------------------------------------------
check('homepage renders', () => exists('index.html'))
check('docs render', () => exists('docs/protocol-services/index.html'))
// Generated by the oauth-client-metadata postBuild plugin. An atproto client_id
// IS this URL, so losing the file silently breaks account login.
check('OAuth client metadata is published', () =>
  exists('oauth-client-metadata.json'),
)

// ---- Blog ----------------------------------------------------------------
check('blog index renders', () => realPage('blog/index.html'))
check('blog archive renders', () => realPage('blog/archive/index.html'))
check('blog RSS feed is published', () => exists('blog/rss.xml'))
check('blog Atom feed is published', () => exists('blog/atom.xml'))
// The feed is only useful if it is discoverable from the blog itself.
check('blog index advertises the RSS feed', () =>
  contains('blog/index.html', 'application/rss+xml'),
)

// The ja locale has no translated posts. The blog plugin globs the default
// content dir for the file list and only overlays per-file localized copies, so
// ja must still render the English posts rather than an empty blog.
check('ja blog falls back to the English posts', () =>
  realPage('ja/blog/index.html'),
)

// ---- head_meta swizzle ---------------------------------------------------
// src/theme/BlogPostPage/Metadata renders front-matter `head_meta` into <head>.
//
// Derived from the posts rather than hardcoded against one of them, so that
// rewriting or replacing the seed post does not quietly stop testing the
// swizzle. If no post uses head_meta at all, that is itself reported: the
// wrapper would then be shipping untested.
function readPostsWithHeadMeta() {
  const blogDir = path.resolve(import.meta.dirname, '..', 'blog')
  const posts = []
  for (const file of fs.readdirSync(blogDir)) {
    if (!/\.mdx?$/.test(file)) continue
    const src = fs.readFileSync(path.join(blogDir, file), 'utf8')
    const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(src)
    if (!fm) continue
    const slug = /^slug:\s*(.+)$/m.exec(fm[1])?.[1].trim()
    // The `head_meta:` block runs to the next line at column 0.
    const block = /^head_meta:\r?\n((?:[ \t]+.*\r?\n?)*)/m.exec(fm[1])
    if (!slug || !block) continue
    const tags = []
    for (const line of block[1].split(/\r?\n/)) {
      const pair = /^\s+([^:]+):\s*(.+?)\s*$/.exec(line)
      if (pair) tags.push([pair[1].trim(), pair[2].replace(/^["']|["']$/g, '')])
    }
    if (tags.length > 0) posts.push({ file, slug, tags })
  }
  return posts
}

const headMetaPosts = readPostsWithHeadMeta()

check('some post exercises head_meta', () =>
  headMetaPosts.length > 0
    ? null
    : 'no blog post declares head_meta, so the BlogPostPage/Metadata swizzle is untested',
)

for (const post of headMetaPosts) {
  const rel = `blog/${post.slug}/index.html`
  for (const [name, content] of post.tags) {
    check(`${post.file}: head_meta ${name} reaches the document head`, () => {
      const html = read(rel)
      if (html === null) return `missing ${rel}`
      const headEnd = html.indexOf('</head>')
      if (headEnd === -1) return 'no </head> in the document'
      // Attribute choice mirrors the wrapper: og:/article:/fb:/profile: are
      // Open Graph properties, everything else is a name= meta.
      const attr = /^(og:|article:|fb:|profile:)/.test(name)
        ? 'property'
        : 'name'
      const needle = `${attr}="${name}" content="${content}"`
      const at = html.indexOf(needle)
      if (at === -1) return `${rel} has no <meta ${needle}>`
      return at < headEnd ? null : `<meta ${needle}> was emitted after </head>`
    })
  }
}

// ---- Blog post chrome ----------------------------------------------------
// The post header shows title, date and byline. Reading time, tags and the
// "Edit this page" row are all deliberately absent — see
// src/theme/BlogPostItem/Header and the blog options in docusaurus.config.js.
check('post header carries our title and meta classes', () => {
  const article = articleOf('blog/welcome/index.html')
  if (article === null) return 'no <article> in blog/welcome/index.html'
  if (!article.includes('bpsBlogTitle'))
    return 'title is missing the bpsBlogTitle class'
  if (!article.includes('bpsBlogInfo'))
    return 'the date is missing the bpsBlogInfo class'
  return null
})
// The byline is post-pages-only, so it needs assertions on both sides: present
// on the post, absent from the index.
//
// Derived from blog/authors.yml and the post's own front matter rather than
// hardcoded, for the same reason the head_meta checks are: reassigning a post
// to a different author should not silently stop testing the byline. Matching
// on a name alone would not do anyway — the authors are Bluesky people and the
// organisation itself, so their names turn up in post titles and prose. The
// profile link is the marker only a byline emits.
function readAuthorsYml() {
  const file = path.resolve(import.meta.dirname, '..', 'blog', 'authors.yml')
  const authors = {}
  let current = null
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    if (/^\s*(#|$)/.test(line)) continue
    const top = /^([A-Za-z0-9_-]+):\s*$/.exec(line)
    if (top) {
      current = top[1]
      authors[current] = {}
      continue
    }
    const field = /^\s+([a-z_]+):\s*(.+?)\s*$/.exec(line)
    if (field && current) authors[current][field[1]] = field[2]
  }
  return authors
}

// The authors of blog/<slug>.md, resolved against authors.yml.
function authorsOfPost(slug) {
  const blogDir = path.resolve(import.meta.dirname, '..', 'blog')
  const all = readAuthorsYml()
  for (const file of fs.readdirSync(blogDir)) {
    if (!/\.mdx?$/.test(file)) continue
    const src = fs.readFileSync(path.join(blogDir, file), 'utf8')
    const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(src)
    if (!fm || /^slug:\s*(.+)$/m.exec(fm[1])?.[1].trim() !== slug) continue
    const keys = /^authors:\s*\[(.+?)\]\s*$/m.exec(fm[1])?.[1]
    if (!keys) return []
    return keys
      .split(',')
      .map((k) => k.trim())
      .map((k) => all[k])
      .filter(Boolean)
  }
  return []
}

const welcomeAuthors = authorsOfPost('welcome')

check('the byline check has an author to assert on', () =>
  welcomeAuthors.length > 0
    ? null
    : 'blog/welcome resolves to no author in blog/authors.yml, so the byline is untested',
)

check('post shows an author byline', () => {
  const article = articleOf('blog/welcome/index.html')
  if (article === null) return 'no <article> in blog/welcome/index.html'
  if (!article.includes('bpsBlogByline'))
    return 'the byline is missing the bpsBlogByline class'
  for (const author of welcomeAuthors) {
    if (!article.includes(author.name))
      return `the byline omits the author name "${author.name}"`
    // Both optional in authors.yml, so only asserted when the entry has them.
    if (author.title && !article.includes(author.title))
      return `the byline omits the author title "${author.title}"`
    if (author.url && !article.includes(author.url))
      return `the byline does not link the author to ${author.url}`
  }
  return null
})

// The byline belongs to the post page. The index is a list of links, and a
// byline under every entry would crowd it — see src/theme/BlogPostItem/Header,
// which renders it only when useBlogPost().isBlogPostPage is true. Without this
// check, a refactor could leak the byline onto the index unnoticed.
check('blog index does not show the byline', () => {
  const article = articleOf('blog/index.html')
  if (article === null) return 'no <article> in blog/index.html'
  return article.includes('bpsBlogByline')
    ? 'a byline is rendered on the blog index'
    : null
})

// ---- Blog index summaries ------------------------------------------------
// The index shows each post's front-matter `description`, not the excerpt that
// runs up to its truncate marker — see src/theme/BlogPostItem/Content.
//
// Only posts that actually declare a description are asserted on: Docusaurus
// computes `description = frontMatter.description ?? excerpt`, so a post
// without one legitimately falls back to its body text and would fail the
// absence check below for the right reason.
function readPostSummaries() {
  const blogDir = path.resolve(import.meta.dirname, '..', 'blog')
  const posts = []
  for (const file of fs.readdirSync(blogDir)) {
    if (!/\.mdx?$/.test(file)) continue
    const src = fs.readFileSync(path.join(blogDir, file), 'utf8')
    const fm = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(src)
    if (!fm) continue
    const description = /^description:\s*(.+)$/m
      .exec(fm[1])?.[1]
      .trim()
      .replace(/^["']|["']$/g, '')
    if (!description) continue

    // A probe for body text that must NOT reach the index: the run of plain
    // prose that opens the first paragraph, cut before any Markdown that would
    // become a tag in the rendered HTML and break a substring match.
    const firstPara = fm[2]
      .split(/\r?\n\s*\r?\n/)
      .map((para) => para.trim())
      .find((para) => para && !/^(#|<|import |\{\/\*|:::|```)/.test(para))
    const leadIn = firstPara?.split(/[[`*_<]/)[0].trim()

    posts.push({ file, description, leadIn })
  }
  return posts
}

const summaryPosts = readPostSummaries()

check('the index summary checks have posts to assert on', () =>
  summaryPosts.length > 0
    ? null
    : 'no blog post declares a description, so the index summary is untested',
)

check('blog index shows each post description', () => {
  const article = articleOf('blog/index.html')
  if (article === null) return 'no <article> in blog/index.html'
  if (!article.includes('bpsBlogSummary'))
    return 'the index summary is missing the bpsBlogSummary class'
  for (const post of summaryPosts) {
    if (!article.includes(post.description))
      return `${post.file}: the description is not on the index`
  }
  return null
})

// The description alone is not enough to prove the swap: it could render while
// the excerpt still sat beneath it. This is the half that pins the behaviour.
check('blog index does not show post body text', () => {
  const article = articleOf('blog/index.html')
  if (article === null) return 'no <article> in blog/index.html'
  for (const post of summaryPosts) {
    // Too short a lead-in would match by coincidence and fail for no reason.
    if (!post.leadIn || post.leadIn.length < 25) continue
    if (article.includes(post.leadIn))
      return `${post.file}: body text ("${post.leadIn.slice(0, 40)}…") is on the index`
  }
  return null
})

// The post page still renders the body, not the description standing in for it.
check('post page still renders its body', () => {
  const article = articleOf('blog/welcome/index.html')
  if (article === null) return 'no <article> in blog/welcome/index.html'
  const welcome = summaryPosts.find((post) => /welcome/.test(post.file))
  if (!welcome?.leadIn) return 'no lead-in probe for the welcome post'
  return article.includes(welcome.leadIn)
    ? null
    : 'the post body is missing from the post page'
})

// showReadingTime is false in docusaurus.config.js: the byline replaced it.
// Checked on both, because the option feeds the index and the post alike.
for (const rel of ['blog/welcome/index.html', 'blog/index.html']) {
  check(`${rel}: no reading time`, () => {
    const article = articleOf(rel)
    if (article === null) return `no <article> in ${rel}`
    return /min read/.test(article) ? 'a reading time is rendered' : null
  })
}

check('post does not show tags', () => {
  const article = articleOf('blog/welcome/index.html')
  if (article === null) return 'no <article> in blog/welcome/index.html'
  return article.includes('/blog/tags/')
    ? 'a tag link is rendered in the post body'
    : null
})
check('post does not offer "Edit this page"', () => {
  const html = read('blog/welcome/index.html')
  if (html === null) return 'missing blog/welcome/index.html'
  return html.includes('Edit this page')
    ? 'the edit link is rendered on the post'
    : null
})
// The feeds credit the author too, from the same blog/authors.yml entry the
// byline reads. Atom rather than RSS: RSS omits an author with no email, and
// the feed's own title would match a bare name search regardless.
check('feed still credits the author', () => {
  if (welcomeAuthors.length === 0) return 'no author to look for'
  for (const author of welcomeAuthors) {
    const problem = contains('blog/atom.xml', author.name)
    if (problem) return problem
  }
  return null
})

// ---- Legacy /blog redirects ----------------------------------------------
// The per-post slugs still belong to atproto.com; reclaiming /blog must not
// have taken them with it. Two spot checks rather than all 27 — enough to catch
// the whole block being dropped.
check('legacy post redirect survives (jetstream)', () =>
  contains('blog/jetstream/index.html', 'https://atproto.com/blog/jetstream'),
)
check('legacy post redirect survives (renamed slug)', () =>
  contains(
    'blog/relay-sync-updates/index.html',
    'https://atproto.com/blog/relay-updates-sync-v1-1',
  ),
)

// Posts carry no tags, so this site generates no /blog/tags page and the path
// goes back to being the old blog's.
check('legacy /blog/tags redirect is restored', () =>
  contains('blog/tags/index.html', 'https://atproto.com/blog'),
)

// ---- Masthead ------------------------------------------------------------
check('masthead links to the blog', () =>
  contains('index.html', 'href="/blog"'),
)
// The Blog link is the one masthead item that stays in the bar at mobile
// widths, where its label is hidden and only this glyph identifies it. If the
// icon stops rendering, the control goes blank on phones and nowhere else —
// the kind of breakage a desktop check would never notice.
check('masthead blog link ships its glyph', () => {
  const html = read('index.html')
  if (html === null) return 'missing index.html'
  const at = html.indexOf('aria-label="Blog"')
  if (at === -1) return 'no aria-label="Blog" in the masthead'
  // Bounded to this anchor. A generous window instead picked up the NEXT nav
  // item's external-link glyph and passed with the Blog icon deleted.
  const end = html.indexOf('</a>', at)
  if (end === -1) return 'the Blog link is never closed'
  return html.slice(at, end).includes('bpsNav__navIcon')
    ? null
    : 'the Blog link renders no glyph'
})

// ---- Report --------------------------------------------------------------
if (failures.length > 0) {
  console.error(
    `\ncheck-build: ${failures.length} of ${checked} checks failed\n`,
  )
  for (const f of failures) console.error(`  ✗ ${f}\n`)
  process.exit(1)
}
console.log(`check-build: ${checked} checks passed`)
